app/models.py
if __name__ == '__main__':
    pass

app/posts/forms.py
from wtforms import Form, StringField, TextAreaField
from wtforms.validators import InputRequired


class PostsForm(Form):
    title = StringField('Title', [InputRequired()])
    body = TextAreaField('Body', [InputRequired()])

app/app.py
if __name__ == '__main__':
    pass

app/main.py
if __name__ == '__main__':
    pass

app/posts/blueprint_post.py
from flask import Blueprint, render_template, request, redirect, url_for

from app import db
from models import Post, Tag
from .forms import PostsForm

from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=["POST", "GET"])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Something bad =(')
        return redirect(url_for('posts.index'))

    form = PostsForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=["POST", "GET"])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first()
    if request.method == 'POST':
        form = PostsForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostsForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def index():
    q = request.args.get('q')

    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    if q:
        print(q)
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)).all()
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = Post.query.paginate(page=page, per_page=5)
    return render_template('posts/index.html', posts=posts, pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    tags = post.tags
    return render_template(r'posts/post_detail.html', post=post, tags=tags)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

app/posts/templates/posts/create_post.html
{% extends "base.html" %}


{% block title %}
   Create new post
{% endblock %}

{% block content_title %}
New post
{% endblock %}

{% block content %}
<div class="col-md-6">
    <form action="{{ url_for('posts.create_post') }}" method="POST">
        {% for f in form %}
        <div class="form-group">
            {{ f.label(class='control-label') }}
            {{ f(class='form-control') }}

        </div>
        {% endfor %}
    <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>
{% endblock %}

app/posts/templates/posts/create_tag.html
{% extends "base.html" %}


{% block title %}
   Create new post
{% endblock %}

{% block content_title %}
New post
{% endblock %}

{% block content %}
<div class="col-md-6">
    <form action="{{ url_for('posts.create_post') }}" method="POST">
        {% for f in form %}
        <div class="form-group">
            {{ f.label(class='control-label') }}
            {{ f(class='form-control') }}

        </div>
        {% endfor %}
    <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>
{% endblock %}

app/posts/templates/posts/edit_post.html
{% extends "base.html" %}


{% block title %}
  Edit post
{% endblock %}

{% block content_title %}
Edit post
{% endblock %}

{% block content %}
<div class="col-md-6">
    <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
        {% for f in form %}
        <div class="form-group">
            {{ f.label(class='control-label') }}
            {{ f(class='form-control') }}

        </div>
        {% endfor %}
    <button type="submit" class="btn btn-primary">Edit</button>
    </form>
</div>
{% endblock %}

app/posts/templates/posts/index.html
{% extends "base.html" %}


{% block title %}

    Blueprint index
{% endblock %}

{% block content_title %}
    Posts
{% endblock %}

{% block content %}
    {% for post in pages.items %}
        <p>
            <a href="{{ url_for('posts.post_detail', slug=post.slug)}}"> {{ post.title }}</a>
        </p>
    {% endfor %}
<nav>
  <ul class="pagination">
    <li class="page-item {% if not pages.has_prev %} disabled {% endif %}">
      <a class="page-link" href="./?page={{ pages.prev_num }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
      {% for page in pages.iter_pages() %}
    <li {% if page == pages.page %} class="page-item" {% endif %}><a class="page-link" href="./?page={{ page }}">{{ page }}</a></li>
      {% endfor %}
    <li class="page-item {% if not pages.has_next %} disabled {% endif %} ">
      <a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
  </ul>
</nav>
{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends "base.html" %}


{% block title %}
   {{ post.title }}
{% endblock %}

{% block content_title %}
{{ post.title }}
{% endblock %}

{% block content %}
<div class="tags">
    {% for tag in tags %}

    <a href="{{ url_for('posts.tag_detail',slug=tag.slug) }}"><span class="badge badge-danger">{{ tag.name }}</span></a>
    {% endfor %}
</div>
<div class="main-content">
    {{post.body}}
</div>
{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends "base.html" %}


{% block title %}
   {{ tag.name }}
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}"
{% endblock %}

{% block content %}
<div class="tags">
    {% for post in posts %}
       <div class="post" ><a href="{{ url_for('posts.post_detail', slug=post.slug)}}">{{ post.title }}</a></div>

</div>
<div class="main-content">
    {{post.body}}
</div>
    {% endfor %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}


        {%endblock %} | Blog app
    </title>
    <!--    Бутстреп -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-inverse bg-dark">
    <a class="navbar-brand" href="{{url_for('index')}}">Main</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('posts.index') }}">Blog <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
            <li class="nav-item">
                <form class="form-inline my-2 my-lg-0" method="GET">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q"
                           value="{{ request.args.get('q', '') }}">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </li>
        </ul>
        <ul class="navbar-nav mr-right">
             <a class="nav-link" href=" {{ url_for('posts.create_post')}}" >+ Create post</a>
        </ul>
    </div>
</nav>
<div class="container">
    <div class="col">
        <h1>
            {% block content_title %}

            {% endblock %}
        </h1>

        {% block content %}

        {% endblock %}

    </div>
</div>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}


{% block title %}
Index page
{% endblock %}

{% block content_title %}
Index page
{% endblock %}

{% block content %}
Some content
{% endblock %}

app/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <ul class="flashes">
    {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{%- endwith %}

app/templates/security/login_user.html
{% extends "base.html" %}


{% block content %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Login') }}</h1>
<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email, class='form-control') }}
  {{ render_field_with_errors(login_user_form.password, class='form-control') }}
  {{ render_field_with_errors(login_user_form.remember, class='form-control') }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit, class='btn btn-success') }}
</form>
{% include "security/_menu.html" %}

{% endblock %}